ROLLBACK;
/*Ejercicio 1*/
INSERT INTO ALUMNO
VALUES( 1, 'Juan Padilla' , '01/01/2001', 954112233);
COMMIT;

/*Ejercicio 2*/
INSERT INTO ALUMNO (NUMMATRICULA, NOMBRE, TELEFONO)
VALUES( 2, 'MARTA SEGURA', 954445566);
COMMIT;

/*Ejercicio 3, preguntar porque da error*/
INSERT INTO PROFESOR
VALUES(1, '28444567T', 'Pepe Martos', 'INFORMATICA', 954987654);
COMMIT;

/*Ejercicio 4*/
INSERT INTO PROFESOR
VALUES(2, '27677777Y', 'David Pascual', 'MATEMATICAS', 954445566);
COMMIT;

/*Ejercicio 5*/
UPDATE PROFESOR
SET ESPECIALIDAD = 'BASE DE DATOS'
WHERE IDPROFESOR = 1;
COMMIT;

/*Ejercicio 6*/
INSERT INTO ASIGNATURA (CODASIGNATURA, NOMBRE, IDPROFESOR)
VALUES(1, 'BASE DE DATOS', SELECT IDPROFESOR
FROM PROFESOR
WHERE ESPECIALIDAD = 'BASE DE DATOS');
COMMIT;