CREATE USER DORMITORIO IDENTIFIED BY DORMITORIO DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TABLESPACE, UNLIMITED TABLESPACE TO DORMITORIO;

CONNECT DORMITORIO/ DORMITORIO;

CREATE TABLESPACE DORMITORIO_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\dormitorio_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TABLE CLIENTE(
NIF VARCHAR2(9),
NOMBRE VARCHAR2(50),
DIRECCION VARCHAR2(50),
TELEFONO NUMBER(9)
) TABLESPACE DORMITORIO_DATOS;

CREATE TABLE MODELODORMITORIO(
CODIGO VARCHAR2(9)
) TABLESPACE DORMITORIO_DATOS;

CREATE TABLE MONTADOR(
NIF VARCHAR2(9),
NOMBRE VARCHAR2(50),
DIRECCION VARCHAR2(50),
TELEFONO NUMBER(9)
) TABLESPACE DORMITORIO_DATOS;

CREATE TABLE COMPRA(
NIF_C VARCHAR2(9),
MODELO VARCHAR2(9),
FECHACOMPRA DATE
) TABLESPACE DORMITORIO_DATOS;

CREATE TABLE MONTA(
MODELO VARCHAR2(9),
NIF_M VARCHAR2(9),
FECHAMONTAJE DATE
) TABLESPACE DORMITORIO_DATOS;

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY(NIF);

ALTER TABLE MODELODORMITORIO ADD CONSTRAINT MODELODORMITORIO_PK PRIMARY KEY(CODIGO);

ALTER TABLE MONTADOR ADD CONSTRAINT MONTADOR_PK PRIMARY KEY(NIF);

ALTER TABLE COMPRA 
ADD CONSTRAINT COMPRA_PK PRIMARY KEY(NIF_C, MODELO, FECHACOMPRA)
ADD CONSTRAINT CLIENTE_FK_COMPRA FOREIGN KEY(NIF_C) REFERENCES CLIENTE(NIF)
ADD CONSTRAINT MODELODORMITORIO_FK_COMPRA FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO(CODIGO);

ALTER TABLE MONTA
ADD CONSTRAINT MONTA_PK PRIMARY KEY (MODELO, NIF_M, FECHAMONTAJE)
ADD CONSTRAINT MODELODORMITORIO_FK_MONTA FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO(CODIGO)
ADD CONSTRAINT MONTADOR_FK_MONTA FOREIGN KEY (NIF_M) REFERENCES MONTADOR(NIF);