CREATE USER EDITORIAL IDENTIFIED BY EDITORIAL DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TABLESPACE, UNLIMITED TABLESPACE TO EDITORIAL;

CREATE TABLESPACE EDITORIAL_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\editorial_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CONNECT EDITORIAL/ EDITORIAL;

CREATE TABLE PERIODISTA(
DNI VARCHAR2(10) CONSTRAINT PERIODISTA_PK PRIMARY KEY,
NOMBRE VARCHAR2 (50),
DIRECCION VARCHAR2 (50),
TELEFONO NUMBER(9),
ESPECIALISTA VARCHAR2 (50)
) TABLESPACE EDITORIAL_DATOS;

CREATE TABLE SUCURSAL(
CODIGO NUMBER(10) CONSTRAINT SUCURSAL_PK PRIMARY KEY,
DIRECCION VARCHAR(50),
TELEFONO NUMBER(9)
) TABLESPACE EDITORIAL_DATOS;

CREATE TABLE EMPLEADO(
DNI VARCHAR2(10) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50), 
DIRECCION VARCHAR2(50), 
TELEFONO NUMBER(9), 
SUCURSAL NUMBER(10) CONSTRAINT SUCURSAL_EMPLEADO_FK REFERENCES SUCURSAL(CODIGO)
) TABLESPACE EDITORIAL_DATOS;

CREATE TABLE REVISTA(
NUMREG NUMBER (10) CONSTRAINT REVISTA_PK PRIMARY KEY,
TITULO VARCHAR2(50),
PERIODICIDAD VARCHAR2(20),
TIPO VARCHAR2(20),
SUCURSAL NUMBER(10) CONSTRAINT SUCURSAL_REVISTA_FK REFERENCES SUCURSAL(CODIGO)
) TABLESPACE EDITORIAL_DATOS;

CREATE TABLE NUMREVISTA(
NUMREG NUMBER(10) CONSTRAINT REVISTA_NUMREVISTA_FK REFERENCES REVISTA(NUMREG),
NUMERO NUMBER(10),
NUMPAGINAS NUMBER(10),
FECHA DATE,
CANTVENDIDAS NUMBER(10),
CONSTRAINT NUMREVISTA_PK PRIMARY KEY(NUMREG, NUMERO)
) TABLESPACE EDITORIAL_DATOS;

CREATE TABLE ESCRIBE(
NUMREG NUMBER(10) CONSTRAINT REVISTA_ESCRIBE_FK REFERENCES REVISTA(NUMREG),
DNIPER VARCHAR2(10) CONSTRAINT PERIODISTA_ESCRIBE_FK REFERENCES PERIODISTA(DNI),
CONSTRAINT ESCRIBE_PK PRIMARY KEY (NUMREG, DNIPER)
) TABLESPACE EDITORIAL_DATOS;

ALTER TABLE EMPLEADO MODIFY NOMBRE NOT NULL;

ALTER TABLE PERIODISTA MODIFY NOMBRE NOT NULL;

ALTER TABLE REVISTA 
MODIFY TITULO NOT NULL
ADD CONSTRAINT REVISTA_PERIODICIDAD_CK CHECK (PERIODICIDAD IN ('Semanal', 'Quincenal', 'Mensual', 'Trimestral', 'Anual'));

ALTER TABLE NUMREVISTA ADD CONSTRAINT NUMREVISTA_NUMPAGINA_CK CHECK (NUMPAGINAS > 0);


