DROP TABLE COCHE.AVALA;
DROP TABLE COCHE.INCLUYE;
DROP TABLE COCHE.RESERVA;
DROP TABLE COCHE.CLIENTE;
DROP TABLE COCHE.COCHE;

DROP TABLESPACE COCHE_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER COCHE CASCADE;
