CREATE USER BANCO IDENTIFIED BY BANCO DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TABLESPACE, UNLIMITED TABLESPACE TO BANCO;

CREATE TABLESPACE BANCO_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\banco_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CONNECT BANCO/ BANCO;

CREATE TABLE SUCURSAL (
CODSUCURSAL NUMBER (10) CONSTRAINT SUCURUSAL_PK PRIMARY KEY,
NOMBRE VARCHAR2(50), 
DIRECCION VARCHAR2 (50), 
LOCALIDAD VARCHAR2 (50)
) TABLESPACE BANCO_DATOS;

CREATE TABLE CLIENTE (
DNI VARCHAR2(10) CONSTRAINT CLIENTE_PK PRIMARY KEY,
NOMBRE VARCHAR2(50),
DIRECCION VARCHAR2(50),
LOCALIDAD VARCHAR2(50),
FECHANC DATE,
SEXO VARCHAR2(6) CONSTRAINT CLIENCE_CK CHECK (SEXO IN ('MUJER', 'HOMBRE'))
) TABLESPACE BANCO_DATOS;

CREATE TABLE CUENTA (
CODSUCURSAL NUMBER(10) CONSTRAINT SUCURSAL_CUENTA_FK REFERENCES SUCURSAL(CODSUCURSAL),
CODCUENTA NUMBER(10),
CONSTRAINT CUENTA_PK PRIMARY KEY (CODSUCURSAL, CODCUENTA)
) TABLESPACE BANCO_DATOS;

CREATE TABLE TRANSACCION (
CODSUCURSAL NUMBER(10),
CODCUENTA NUMBER(10),
NUMTRANSACCION NUMBER(10),
FECHA DATE NOT NULL,
CANTIDAD NUMBER(5,2) DEFAULT 0.00, /* 5 digitos enteros y 2 decimales*/
TIPO VARCHAR2(10)  CONSTRAINT TRANSACCION_CK CHECK (TIPO IN ('INGRESO', 'GASTO', 'TARJETA', 'HIPOTECA')) DEFAULT GASTO,
CONSTRAINT TRANSACCION_PK PRIMARY KEY(CODSUCURSAL, CODCUENTA, NUMTRANSACCION),
CONSTRAINT CUENTA_TRANSACCION_FK FOREIGN KEY (CODSUCURSAL, CODCUENTA) REFERENCES CUENTA(CODSUCURSAL, CODCUENTA)
) TABLESPACE BANCO_DATOS;

CREATE TABLE CLICUENTA (
CODSUCURSAL NUMBER(10),
CODCUENTA NUMBER(10),
DNI VARCHAR2(10),
CONSTRAINT CLICUENTA PRIMARY KEY(CODSUCURSAL, CODCUENTA, DNI),
CONSTRAINT CUENTA_CLICUENTA_FK FOREIGN KEY (CODSUCURSAL, CODCUENTA) REFERENCES CUENTA(CODSUCURSAL, CODCUENTA),
CONSTRAINT CLIENTE_CLICUENTA_FK FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI)
) TABLESPACE BANCO_DATOS;

ALTER TABLE CLIENTE ADD FECHAALTA DATE;

/* Ejericico3 */

ALTER TABLE TRANSACCION
DROP CONSTRAINT CUENTA_TRANSACCION_FK;

ALTER TABLE TRANSACCION
ADD CONSTRAINT CUENTA_TRANSACCION_FK FOREIGN KEY (CODSUCURSAL, CODCUENTA) REFERENCES CUENTA(CODSUCURSAL, CODCUENTA) ON DELETE CASCADE;

/* Ejercicio4 */

CREATE SEQUENCE SEC_CODSUCURSAL
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    MINVALUE 1
    NOCYCLE;

/* Ejercicio5 */

ALTER TABLE CLIENTE
DROP CONSTRAINT CLIENTE_CK;

/* Ejercicio6 */
DROP TABLE BANCO.CLICUENTA;
DROP TABLE BANCO.TRANSACCION;
DROP TABLE BANCO.CUENTA;
DROP TABLE BANCO.SUCURSAL;
DROP TABLE BANCO.CLIENTE;
