DROP TABLE CLUB_NAUTICO.ES_PROPIETARIO;
DROP TABLE CLUB_NAUTICO.AMARRE;
DROP TABLE CLUB_NAUTICO.SE_ENCARGA;
DROP TABLE CLUB_NAUTICO.EMBARCACION;
DROP TABLE CLUB_NAUTICO.EMPLEADO;
DROP TABLE CLUB_NAUTICO.ZONA;
DROP TABLE CLUB_NAUTICO.SOCIO;
DROP SEQUENCE CLUB_NAUTICO.SEC_CODIGO; 

DROP TABLESPACE CLUB_NAUTICO_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER CLUB_NAUTICO;

