DROP TABLE EDITORIAL.NUMREVISTA;
DROP TABLE EDITORIAL.ESCRIBE;
DROP TABLE EDITORIAL.REVISTA;
DROP TABLE EDITORIAL.EMPLEADO;
DROP TABLE EDITORIAL.SUCURSAL;
DROP TABLE EDITORIAL.PERIODISTA;

DROP TABLESPACE EDITORIAL_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER EDITORIAL;
