DROP TABLE DORMITORIO.COMPRA;
DROP TABLE DORMITORIO.MONTA;
DROP TABLE DORMITORIO.CLIENTE;
DROP TABLE DORMITORIO.MODELODORMITORIO;
DROP TABLE DORMITORIO.MONTADOR;

DROP TABLESPACE DORMITORIO_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER DORMITORIO;