CREATE USER EMPRESA IDENTIFIED BY EMPRESA DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TABLESPACE, UNLIMITED TABLESPACE TO EMPRESA;

CREATE TABLESPACE EMPRESA_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\empresa_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CONNECT EMPRESA/ EMPRESA;

CREATE TABLE REGION(
CODREGION NUMBER(10) CONSTRAINT REGION_PK PRIMARY KEY,
NOMBRE VARCHAR2(50)
) TABLESPACE EMPRESA_DATOS;

CREATE TABLE PROVINCIA (
CODPROVINCIA NUMBER (10) CONSTRAINT PROVINCIA_PK PRIMARY KEY,
NOMBRE VARCHAR2(50), 
CODREGION NUMBER(10) CONSTRAINT REGION_PROVINCIA_FK REFERENCES REGION(CODREGION)
) TABLESPACE EMPRESA_DATOS;

CREATE TABLE LOCALIDAD (
CODLOCALIDAD NUMBER (10) CONSTRAINT LOCALIDAD_PK PRIMARY KEY,
NOMBRE VARCHAR(50),
CODPROVINCIA NUMBER(10) CONSTRAINT PROVINCIA_LOCALIDAD_PK REFERENCES PROVINCIA(CODPROVINCIA)
) TABLESPACE EMPRESA_DATOS;

CREATE TABLE EMPLEADO(
CODIGO NUMBER(10) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
DNI VARCHAR2(9)CONSTRAINT EMPLEADO_DNI_UK UNIQUE,
NOMBRE VARCHAR2(50),
FECHANACIMIENTO DATE,
TELEFONO NUMBER (9),
SALARIO NUMBER(10),
CODLOCALIDAD NUMBER (10) CONSTRAINT LOCALIDAD_EMPLEADO_FK REFERENCES LOCALIDAD(CODLOCALIDAD)
) TABLESPACE EMPRESA_DATOS;