DROP TABLE EMPRESA.EMPLEADO;
DROP TABLE EMPRESA.LOCALIDAD;
DROP TABLE EMPRESA.PROVINCIA;
DROP TABLE EMPRESA.REGION;

DROP TABLESPACE EMPRESA_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER EMPRESA;