DROP TABLE INSTITUTO.RECIBE;
DROP TABLE INSTITUTO.ASIGNATURA;
DROP TABLE INSTITUTO.ALUMNO;
DROP TABLE INSTITUTO.PROFESOR; 

DROP TABLESPACE INSTITUTO_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER INSTITUTO;
