DROP TABLE BANCO.CLICUENTA;
DROP TABLE BANCO.TRANSACCION;
DROP TABLE BANCO.CUENTA;
DROP TABLE BANCO.SUCURSAL;
DROP TABLE BANCO.CLIENTE;





DROP TABLESPACE BANCO_DATOS INCLUDING CONTENTS AND DATAFILES;

DROP USER BANCO CASCADE;
