CREATE USER DEPARTAMENTO IDENTIFIED BY DEPARTAMENTO DEFAULT TABLESPACE USERS;

GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TABLESPACE, UNLIMITED TABLESPACE TO DEPARTAMENTO;

CONNECT DEPARTAMENTO/ DEPARTMENTO;

CREATE TABLESPACE DEPARTAMENTO_DATOS DATAFILE
'C:\oraclexe\app\oracle\oradata\XE\departamento_datos01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE TABLE DEPARTAMENTO(
IDENTIFICACIONDEP NUMBER (10) CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(50),
UBICACION VARCHAR2(50)
) TABLESPACE DEPARTAMENTO_DATOS;

CREATE TABLE EMPLEADO(
IDENTIFICACIONEMP NUMBER (10) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
DNI VARCHAR2(11) CONSTRAINT DNI_EMPLEADO_UK UNIQUE,
NOMBRE VARCHAR2(50),
SALARIO NUMBER(10),
TELEFONO NUMBER (10),
IDDEP NUMBER (10) CONSTRAINT DEPARTAMENTO_EMPLEADO_PK REFERENCES DEPARTAMENTO(IDENTIFICACIONDEP)
) TABLESPACE DEPARTAMENTO_DATOS;

CREATE TABLE JEFE(
IDJEFE NUMBER(10) CONSTRAINT JEFE_PK PRIMARY KEY,
DNI VARCHAR2(11) CONSTRAINT DNI_JEFE_UK UNIQUE,
NOMBRE VARCHAR2(50),
SALARIO NUMBER(10),
TELEFONO NUMBER (10),
IDDEP NUMBER (10) CONSTRAINT DEPARTAMENTO_JEFE_FK REFERENCES DEPARTAMENTO(IDENTIFICACIONDEP) CONSTRAINT DEPARTAMENTO_JEFE_UK UNIQUE
) TABLESPACE DEPARTAMENTO_DATOS;