/*EJERCICIO 57*/
SELECT nif, razon_social, direccion
FROM Cliente
WHERE nif IN ( SELECT DISTINCT nif FROM Pedido
WHERE total_pedido > 200 );

/*EJERCICIO 58*/
SELECT REFERENCIA, DESCRIPCION
FROM ARTICULO ART
WHERE EXISTENCIAS > (SELECT SUM (UNIDADES)
FROM LPEDIDO 
WHERE REFERENCIA = ART.REFERENCIA);

--LO PRUEBO
SELECT SUM(UNIDADES)
FROM LPEDIDO 
WHERE REFERENCIA = 'CONF0003';

/*EJERCICIO 59*/
SELECT NIF, RAZON_SOCIAL
FROM CLIENTE CLI
WHERE VENTAS < (SELECT AVG(TOTAL_PEDIDO)
FROM PEDIDO
WHERE CLIENTE = CLI.NIF);

/*EJERCICIO 60*/
SELECT NPEDIDO, CLIENTE, FECHA
FROM PEDIDO CLI
WHERE TOTAL_PEDIDO >(SELECT AVG(TOTAL_PEDIDO)
FROM PEDIDO
WHERE CLIENTE = CLI.CLIENTE);

/*EJERCICO 61*/
SELECT *
FROM LALBARAN;
SELECT * 
FROM LPEDIDO;

SELECT REFERENCIA, UNIDADES * (PRECIO - PRECIO * DTO)
FROM LALBARAN
WHERE  UNIDADES * (PRECIO - PRECIO * DTO) < (SELECT AVG(UNIDADES * (PRECIO - PRECIO * DTO))
FROM LPEDIDO);

/*EJERCICIO 62*/
SELECT REFERENCIA, UNIDADES * (PRECIO - PRECIO * DTO)
FROM LALBARAN LAL
WHERE  UNIDADES * (PRECIO - PRECIO * DTO) < (SELECT AVG(UNIDADES * (PRECIO - PRECIO * DTO))
FROM LPEDIDO
WHERE REFERENCIA = LAL.REFERENCIA);

SELECT *
FROM ARTICULO;

/*EJERCICIO 63*/
SELECT*
FROM LALBARAN;

SELECT * 
FROM LPEDIDO;

SELECT *
FROM LALBARAN
WHERE DTO < (SELECT MIN(DTO)
FROM LPEDIDO);

/*EJERCICIO 64*/
SELECT *
FROM LALBARAN 
WHERE DTO < (SELECT AVG(DTO)
FROM LPEDIDO
WHERE REFERENCIA = 'BEBI0001');

/*EJERCICIO 65*/
SELECT *
FROM EFECTO;

SELECT NFACTURA, NEFECTO, FECHA_VTO
FROM EFECTO EFE
WHERE FECHA_VTO != (SELECT FECHA
FROM FACTURA
WHERE NFACTURA = EFE.NFACTURA);

SELECT*
FROM FACTURA;

/*EJERCICIO 66*/
SELECT DESCRIPCION
FROM CATEGORIA
WHERE CATEGORIA = (SELECT CATEGORIA
FROM ARTICULO ART
WHERE ART.REFERENCIA = 'BEBI0001');

SELECT *
FROM CATEGORIA;

SELECT *
FROM ARTICULO;

/*EJERCICIO 67*/
SELECT *
FROM PEDIDO;

SELECT CLIENTE
FROM PEDIDO
WHERE EXTRACT (MONTH FROM FECHA) = 01;

/*EJERCICIO 68*/
SELECT *
FROM PEDIDO;

SELECT * 
FROM CLIENTE;

SELECT *
FROM PEDIDO
WHERE CLIENTE = (SELECT NIF
FROM CLIENTE
WHERE RAZON_SOCIAL = 'Hiper Barato');

/*EJERCICIO 69*/
SELECT*
FROM FORMA_PAGO;

SELECT *
FROM PEDIDO;

SELECT * 
FROM PEDIDO
WHERE FORMA_PAGO = (SELECT FORMA_PAGO
FROM FORMA_PAGO
WHERE DESCRIPCION = 'Contado');

/*EJERICICO 70*/
SELECT *
FROM ARTICULO;
SELECT * 
FROM LPEDIDO;

SELECT REFERENCIA, DESCRIPCION, PRECIO_VENTA
FROM ARTICULO
WHERE REFERENCIA NOT IN (SELECT REFERENCIA
FROM LPEDIDO);

/*EJERICICIO 71*/
SELECT *
FROM ALBARAN;

SELECT NALBARAN, FECHA, CLIENTE
FROM ALBARAN
WHERE CLIENTE NOT IN (SELECT CLIENTE
FROM FACTURA);

SELECT *
FROM FACTURA;

/*EJERCICIO 72*/
SELECT *
FROM PEDIDO;

SELECT *
FROM REPRESENTANTE;

SELECT NIF, NOMBRE, TELEFONO
FROM REPRESENTANTE
WHERE NIF IN (SELECT REPRESENTANTE
FROM PED_REP); 

SELECT *
FROM PED_REP;

/*HASTA *EL 76 HACER CON EXISTS Y CON IN */
 
/*EJERCICIO 73*/
SELECT NIF, NOMBRE
FROM REPRESENTANTE
WHERE EXISTS (SELECT REPRESENTANTE
FROM PED_REP
WHERE REPRESENTANTE = NIF); 

SELECT NIF, NOMBRE
FROM REPRESENTANTE
WHERE NIF IN (SELECT REPRESENTANTE
FROM PED_REP); 

/*EJERCICIO 74*/

SELECT *
FROM CLIENTE;

SELECT *
FROM ALBARAN;

SELECT NIF, RAZON_SOCIAL
FROM CLIENTE 
WHERE EXISTS (SELECT CLIENTE 
FROM ALBARAN 
GROUP BY CLIENTE
HAVING SUM(TOTAL_ALBARAN)> 200  AND  CLIENTE = NIF);

SELECT NIF, RAZON_SOCIAL
FROM CLIENTE
WHERE NIF IN (SELECT CLIENTE
FROM ALBARAN
GROUP BY CLIENTE
HAVING SUM (TOTAL_ALBARAN ) > 200);

/*EJERCICIO 75*/

SELECT *
FROM FACTURA;

SELECT *
FROM EFECTO;

SELECT NFACTURA, FECHA
FROM FACTURA
WHERE  NOT EXISTS (SELECT NFACTURA
FROM EFECTO EFE
WHERE EFE.NFACTURA = NFACTURA);

SELECT NFACTURA, FECHA
FROM FACTURA
WHERE  NFACTURA NOT IN (SELECT NFACTURA
FROM EFECTO);

/*EJERCICIO 76*/

SELECT *
FROM CATEGORIA;

SELECT *
FROM ARTICULO;

SELECT CATEGORIA, DESCRIPCION
FROM CATEGORIA CA
WHERE EXISTS (SELECT CATEGORIA
FROM ARTICULO ART
WHERE PRECIO_VENTA > 5 AND ART.CATEGORIA = CA.CATEGORIA );

SELECT CATEGORIA, DESCRIPCION
FROM CATEGORIA
WHERE CATEGORIA IN (SELECT CATEGORIA
FROM ARTICULO
WHERE PRECIO_VENTA > 5);



